[build]
  base = "."
  command = "npm run build"
  publish = ".next"
  package = "."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22.13.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
